/** Controlador de presentación de la aplicación. */
window.UGE = window.UGE || {};
UGE.AppController = class AppController {
  constructor(store, engine) {
    this.store=store;this.engine=engine;this.searchService=new UGE.SearchService(store);
    this.period='all';this.language='all';this.subjects=[];this.currentSubject=null;
    this.currentGrade='su';this.subjectLanguage='all';this.subjectPeriod='all';
  }
  languageText(){return this.language==='es'?'Castellano':this.language==='ca'?'Catalán':'Castellano y catalán';}
  currentRows(){let rows=this.currentSubject.all;if(this.subjectLanguage==='es'||this.subjectLanguage==='ca')rows=rows.filter(row=>row.language===this.subjectLanguage);return UGE.periodRows(rows,this.subjectPeriod);}
  render(){const rows=this.store.getRows({language:this.language,period:this.period});this.subjects=this.engine.enrichSubjects(this.store.getSubjects({language:this.language,period:this.period}));
    UGE.$('#records').textContent=rows.length;UGE.$('#subjects').textContent=this.subjects.length;UGE.$('#semesters').textContent=new Set(rows.map(row=>row.semester)).size;UGE.$('#version').textContent=this.store.payload.dataset_version||this.store.payload.generated_at?.slice(0,10)||'sin versión';UGE.$('#context').textContent=`${this.subjects[0]?.degree||'UOC'} · Vista general · ${this.languageText()}`;
    const rank=[...this.subjects].sort((a,b)=>b.su-a.su);UGE.$('#rank').innerHTML=rank.map((subject,index)=>`<div class="rankitem" data-k="${subject.key}"><span class="muted">${index+1}</span><div><b>${UGE.escapeHtml(subject.name)}</b><div class="muted">${this.engine.availableLanguages(subject)}</div><div class="bar"><i style="width:${UGE.clamp(subject.su,0,100)}%"></i></div></div><b>${subject.su.toFixed(0)}%</b></div>`).join('');
    UGE.$('#quick').innerHTML=[...this.subjects].sort((a,b)=>a.su-b.su).slice(0,4).map(subject=>`<div class="qrow" data-k="${subject.key}"><div><b>${UGE.escapeHtml(subject.name)}</b><div class="muted">${subject.code} · ${this.engine.availableLanguages(subject)}</div></div><span class="badge">${subject.su.toFixed(0)}% SU</span></div>`).join('');
    const grouped=rows.reduce((acc,row)=>{(acc[row.semester] ||= []).push(Number(row.su)||0);return acc;},{});UGE.lineChart('#globalchart',[{name:'Suspensos',data:Object.fromEntries(Object.entries(grouped).map(([key,values])=>[key,UGE.mean(values)])),css:'var(--d)'}]);
  }
  sync(){UGE.$$('[data-sub-lang]').forEach(button=>button.classList.toggle('active',button.dataset.subLang===this.subjectLanguage));UGE.$$('[data-sub-period]').forEach(button=>button.classList.toggle('active',button.dataset.subPeriod===this.subjectPeriod));}
  show(code){const subject=this.store.getSubject(code);if(!subject)return;this.currentSubject=subject;this.currentGrade='su';this.subjectLanguage='all';this.subjectPeriod='all';UGE.$('#dash').classList.remove('active');UGE.$('#subject').classList.add('active');this.sync();this.renderSubject();location.hash='asignatura/'+encodeURIComponent(code);}
  home(){UGE.$('#subject').classList.remove('active');UGE.$('#dash').classList.add('active');this.currentSubject=null;location.hash='';}
  renderSubject(){const rows=this.currentRows(),metrics=this.engine.metrics(rows),languageName=this.subjectLanguage==='all'?'Ambos idiomas':this.subjectLanguage==='es'?'Castellano':this.subjectLanguage==='ca'?'Catalán':'Comparación ES/CA';UGE.$('#stitle').textContent=this.currentSubject.name;UGE.$('#smeta').textContent=`Código ${this.currentSubject.code} · ${this.engine.availableLanguages(this.currentSubject)} · ${rows.length} registros visibles`;UGE.$('#subjectcontext').textContent=`${this.currentSubject.degree} · ${this.currentSubject.name} · ${languageName}`;UGE.$('#difficulty').textContent=metrics.su.toFixed(1)+'%';UGE.GRADES.forEach(grade=>UGE.$('#m'+grade).textContent=metrics[grade].toFixed(1)+'%');this.renderSummary(rows);this.renderSubjectChart();this.renderHistory(rows);}
  renderSummary(rows){const {metrics,deviation,delta}=this.engine.stats(rows),difficulty=this.engine.difficulty(metrics.su),stability=deviation<2?'Muy estable':deviation<5?'Estable':deviation<9?'Variable':'Muy variable',trend=delta<=-3?'Mejora':delta>=3?'Empeora':'Estable';let text=`La asignatura presenta una dificultad ${difficulty.toLowerCase()}, con un ${metrics.su.toFixed(1)} % de suspensos. Su comportamiento es ${stability.toLowerCase()}. `;text+=trend==='Mejora'?`Los suspensos descienden ${Math.abs(delta).toFixed(1)} puntos.`:trend==='Empeora'?`Los suspensos aumentan ${Math.abs(delta).toFixed(1)} puntos.`:'No se aprecia una tendencia clara.';if(this.subjectLanguage==='compare'&&this.currentSubject.languages.es.length&&this.currentSubject.languages.ca.length){const es=this.engine.metrics(UGE.periodRows(this.currentSubject.languages.es,this.subjectPeriod)).su,ca=this.engine.metrics(UGE.periodRows(this.currentSubject.languages.ca,this.subjectPeriod)).su,difference=es-ca;text+=` La diferencia media entre idiomas es de ${Math.abs(difference).toFixed(1)} puntos, con más suspensos en ${difference>0?'castellano':'catalán'}.`;}
    UGE.$('#summaryText').textContent=text;UGE.$('#difficultyLabel').textContent=difficulty;UGE.$('#difficultyBar').style.width=UGE.clamp(metrics.su,0,100)+'%';UGE.$('#stabilityLabel').textContent=stability;UGE.$('#stabilityBar').style.width=UGE.clamp(100-deviation*8,5,100)+'%';UGE.$('#trendLabel').textContent=trend;UGE.$('#trendBar').style.width=UGE.clamp(50-delta*5,5,100)+'%';}
  renderSubjectChart(){const rows=this.currentRows(),series=[];UGE.$('#subjectcharttitle').textContent='Evolución de '+UGE.GRADE_LABELS[this.currentGrade];UGE.$('#chartgradebadge').textContent=UGE.GRADE_SHORT[this.currentGrade];UGE.$$('.metric').forEach(item=>item.classList.toggle('active',item.dataset.grade===this.currentGrade));if(this.subjectLanguage==='compare'){const es=UGE.periodRows(this.currentSubject.languages.es||[],this.subjectPeriod),ca=UGE.periodRows(this.currentSubject.languages.ca||[],this.subjectPeriod);if(es.length)series.push({name:'Castellano',data:this.engine.series(es,this.currentGrade),css:'var(--a)'});if(ca.length)series.push({name:'Catalán',data:this.engine.series(ca,this.currentGrade),css:'var(--d)'});UGE.$('#subjectcharthelp').textContent=`Comparación directa: ${es.length} registros en castellano y ${ca.length} en catalán`;UGE.$('#legend').innerHTML='<span>Castellano</span><span class="ca">Catalán</span>';}else{series.push({name:'Media',data:this.engine.series(rows,this.currentGrade),css:this.currentGrade==='su'?'var(--d)':'var(--a)'});UGE.$('#subjectcharthelp').textContent='Pulsa en MH, EX, NO, AP o SU para cambiar la serie';UGE.$('#legend').innerHTML='';}UGE.lineChart('#subjectchart',series);}
  renderHistory(rows){const ordered=[...rows].sort((a,b)=>UGE.semesterKey(b.semester)-UGE.semesterKey(a.semester)||a.language.localeCompare(b.language));UGE.$('#hist').innerHTML=ordered.map(row=>`<tr><td>${row.semester}</td><td>${row.language==='es'?'Castellano':'Catalán'}</td>${UGE.GRADES.map(grade=>`<td>${Number(row[grade]).toFixed(1)}%</td>`).join('')}</tr>`).join('');UGE.$$('.history th,.history td').forEach(cell=>cell.classList.remove('selected'));const column={mh:3,ex:4,no:5,ap:6,su:7}[this.currentGrade];UGE.$$('.history tr').forEach(row=>{if(row.children[column-1])row.children[column-1].classList.add('selected');});}
  search(query){const box=UGE.$('#results');if(!String(query).trim()){box.classList.remove('open');return;}const results=this.searchService.find(query,this.subjects);box.innerHTML=results.map(subject=>`<div class="result" data-k="${subject.key}"><b>${UGE.escapeHtml(subject.name)}</b><div class="muted">${subject.code} · ${this.engine.availableLanguages(subject)} · ${subject.su.toFixed(0)}% suspensos</div></div>`).join('')||'<div class="result muted">Sin coincidencias</div>';box.classList.add('open');}
};
